version: '3.8'
services:
  hugo-dev:
    image: ghcr.io/gohugoio/hugo:v0.148.1
    container_name: hugo_dev
    working_dir: /src
    volumes:
      - .:/src # Maps the current directory (host) to /src (container)
    ports:
      - "1313:1313"
    command: server --source /src --bind 0.0.0.0
