version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.hugo
    ports:
      - "1313:1313"

  tests:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    depends_on:
      - web
