version: '3.8' # Keep this for now, the warning is minor.
services:
  hugo-dev:
    build: . # Instructs Compose to build the image from the Dockerfile in the current directory
    container_name: hugo_dev
    working_dir: /src
    ports:
      - "1313:1313"
    # The command is now defined in the Dockerfile's CMD instruction
    develop:
      watch:
        - path: . # Watch the entire current directory on the host
          action: rebuild # <--- IMPORTANT: Rebuild the image and restart the container on changes
