baseURL = 'https://fleig.us/'
languageCode = 'en-us'
title = 'Fleig Family Website'
disableKinds = ['taxonomy', 'term']

[Params]
  names = ["amanda", "roger"]
  title = 'Fleig Family Website'

[markup]
  [markup.sass]
    outputStyle = "compressed"
