baseURL = 'https://fleig.us/'
languageCode = 'en-us'
title = 'Fleig Family Website'

[Params]
  names = ["amanda", "roger"]
  title = 'Fleig Family Website'
  debug = false

[markup]
  [markup.sass]
    outputStyle = "compressed"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[taxonomies]
  tag = "tags"
