name: Deploy Hugo Site to Pages

on:
  push:
    branches:
      - main # Trigger deployment when changes are pushed to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest
    
    # Give the build job permissions to upload artifacts and use GitHub's token
    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Hugo environment
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          # Use the 'extended' version if your site uses features like Sass/SCSS
          hugo-version: '0.148.1' # Specify the version of Hugo you want to use
          extended: true

      # Build the Hugo site
      - name: Build site
        run: hugo --minify

      # Prepare the generated 'public' directory as a Pages artifact
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  # Deployment job: Runs after the build job is successful
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      contents: read
      pages: write
      id-token: write

    # Use the official GitHub Pages deployment action
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
